on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    outputs: 
      artifact_name: ${{ steps.set-version.outputs.service_name }}
    steps:
      - id: set-version
        run: |
          version=$(date +%Y%m%d-%H%M%S)
          service_name="my-app.${VERSION}.tar.gz"
          echo $service_name >> $GITHUB_OUTPUT
      
      - id: build
        run: |
          tar -czf $service_name src/app.py 
      
      - uses: actions/upload-artifact@v4
        with:
          name: $service_name
          path: .
  
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: |          
          echo "Artifact: ${{ needs.build.outputs.artifact-name }}"